### ISSUE TITLE
com.github.Eloston.UngoogledChromium doesn't start

### ISSUE THREAD

**Issue by alandiwix** [flathub/com.github.Eloston.UngoogledChromium#27] opened 2021-05-07 06:36 UTC
com.github.Eloston.UngoogledChromium doesn't start without displaying any critical error, only
```
(chrome:2): Gdk-WARNING **: 06:07:37.630: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
```
org.chromium.Chromium however works perfectly fine (while also beginning with the same warning)
I'm running both with ` --enable-features=UseOzonePlatform --ozone-platform=wayland`

**Comment by rany2** [comment] 2021-05-09 13:12
I don't have much info to help. Could you give me some info about your setup?

**Comment by rany2** [comment] 2021-05-12 21:34
Closing.. Feel free to reopen if you're still here.

**Comment by alandiwix** [comment] 2021-08-24 08:40
@rany2 it's wayland (sway) on Alpine
Ungoogled Chromium doesn't even provide any reason of crash. Not sure how to debug with such scarce info, so I just gave up for a time in hope this resolves itself, however this is not the case.

**Comment by rany2** [comment] 2021-08-24 08:57
@alandiwix

**Comment by rany2** [comment] 2021-08-24 08:59
@alandiwix IIRC I had the same issue too on Alpine, I think I fixed it by enabling and starting `dbus`:

```
rc-update add dbus default
rc-service dbus start
```

**Comment by sambonbonne** [comment] 2021-09-14 07:09
I'm a user of Unggogled Chromium on Gnome Wayland. I start it with the app menu and I **don't** have this issue. 
If I can help giving more information about my environment or trying to launch Ungoogled Chromium with a specific command to see if I can reproduce the error, feel free to ask.

**Comment by refi64** [comment] 2021-09-14 21:45
@alandiwix Well, no core dump, odd...one more thing to try, can you start it with `flatpak run --env=G_MESSAGES_DEBUG=cobalt com.github.Eloston.UngoogledChromium` and post the output?

**Comment by rany2** [comment] 2021-10-31 19:31
Closing because you haven't responded.

**Closed by rany2** 2021-10-31 19:31 UTC
